name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get -y install qmake6 qt6-base-dev
    - run: qmake6
    - name: Build
      run: |
        make
    - run: ls -l
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: spreadsheet-bin
        path: spreadsheet
